let texto: string = 'Hola mundo';
let numero: number = 123;
let booleano: boolean = true;
let hoy: Date = new Date();
let cualquierCosita: any = 'Hola';
cualquierCosita = 123;
let cualquiera:unknown = 'Hola';
cualquiera = 123;
cualquiera = true;